### ISSUE TITLE
MethodError for is_manifest_current()

### ISSUE THREAD

**Issue by tpoisot** [PumasAI/QuartoNotebookRunner.jl#197]
I'm trying to run a notebook on Julia 1.11 / Quarto 1.5.57, and it seems that there's an issue with the `is_manifest_current` method. Is this a QuartoNotebookRunner issue, or a quarto issue?

~~~
Starting julia control server process. This might take a while...
ERROR: LoadError: MethodError: no method matching is_manifest_current()
The function `is_manifest_current` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  is_manifest_current(::Pkg.Types.Context)
   @ Pkg ~/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/share/julia/stdlib/v1.11/Pkg/src/API.jl:489
  is_manifest_current(::AbstractString)
   @ Pkg ~/.julia/juliaup/julia-1.11.0+0.x64.linux.gnu/share/julia/stdlib/v1.11/Pkg/src/API.jl:490

Stacktrace:
 [1] top-level scope
   @ ~/opt/quarto-1.5.57/share/julia/ensure_environment.jl:17
in expression starting at /home/tpoisot/opt/quarto-1.5.57/share/julia/ensure_environment.jl:17
ERROR: Ensuring an updated julia server environment failed

Stack trace:
    at ensureQuartoNotebookRunnerEnvironment (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:41527:15)
    at eventLoopTick (ext:core/01_core.js:153:7)
    at async startOrReuseJuliaServer (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:41435:13)
    at async getJuliaServerConnection (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:41548:24)
    at async executeJulia (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:41607:18)
    at async Object.execute (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:41352:20)
    at async renderExecute (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:78033:27)
    at async renderFileInternal (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:78201:43)
    at async renderFiles (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:78069:17)
    at async renderProject (file:///home/tpoisot/opt/quarto-1.5.57/bin/quarto.js:78479:25)
~~~

The same but using the lts version of julia (1.10) works.

**Comment by jkrumbiegel** [comment]
This error was already fixed upstream in quarto https://github.com/quarto-dev/quarto-cli/pull/10244, but there's other issues with QuartoNotebookRunner in 1.11 that will have to be merged and tagged and upstreamed to quarto https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/191
