### ISSUE TITLE
QNR fails on julia nightly due to world age issues

### ISSUE THREAD

**Issue by felixcremer** [PumasAI/QuartoNotebookRunner.jl#214]
While working on #210 I ran into the following error in julia nightly. The error happens with an empty Project.toml and the same basic notebook file as in #210:

```julia
(base) fcremer@javorina:~/Documents/quartotest$ QUARTO_JULIA=$(julia +nightly -e "println(Sys.BINDIR)")/julia quarto render index.qmd --execute-debug
- Transport file /run/user/1001/julia/julia_transport.txt doesn't exist
Starting julia control server process. This might take a while...
- Starting detached julia server through julia, once transport file exists, server should be running.
- Transport file did not exist, yet.
- Transport file did not exist, yet.
- Transport file did not exist, yet.
- Transport file did not exist, yet.
- Transport file did not exist, yet.
- Transport file did not exist, yet.
- Transport file read successfully.
Julia server process started.
- Connecting to server at port 8000, pid 30405
- write command "isready" to socket server
- received server response
- Transport file read successfully.
- write command "isopen" to socket server
- received server response
- write command "run" to socket server
- received server response
ERROR: Julia server returned error after receiving "run" command:
Failed to run notebook: /home/fcremer/Documents/quartotest/index.qmd
ERROR: Remote exception from Malt.Worker on port 9432 with PID 30432:

MethodError: no method matching define_notebook_module!(::Module)
The applicable method may be too new: running in world age 23638, while current world is 23665.

Closest candidates are:
  define_notebook_module!(::Any) (method too new to be called from this world context.)
   @ QuartoNotebookWorker ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/QuartoNotebookWorker/src/NotebookState.jl:22
  define_notebook_module!() (method too new to be called from this world context.)
   @ QuartoNotebookWorker ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/QuartoNotebookWorker/src/NotebookState.jl:22

Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/worker.jl:28
 [2] eval(m::Module, e::Any)
   @ Core ./boot.jl:461
 [3] (::var"#handle##0#handle##1"{Sockets.TCPSocket, UInt64, Bool, @Kwargs{}, Tuple{Module, Expr}, typeof(Core.eval)})()
   @ Main ~/.julia/packages/Malt/YJ2Ml/src/worker.jl:120
Stacktrace:
  [1] unwrap_worker_result(worker::Malt.Worker, result::Malt.WorkerResult)
    @ Malt ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:50
  [2] _wait_for_response(worker::Malt.Worker, msg_id::UInt64)
    @ Malt ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:325
  [3] _send_receive
    @ ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:336 [inlined]
  [4] #remote_call_fetch#48
    @ ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:406 [inlined]
  [5] remote_call_fetch
    @ ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:405 [inlined]
  [6] remote_eval_fetch
    @ ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:484 [inlined]
  [7] remote_eval_fetch
    @ ~/.julia/packages/Malt/YJ2Ml/src/Malt.jl:485 [inlined]
  [8] init!
    @ ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:112 [inlined]
  [9] QuartoNotebookRunner.File(path::String, options::Dict{String, Any})
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:26
 [10] (::QuartoNotebookRunner.var"#35#36"{Bool, Dict{String, Any}, Server, String})()
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:1155
 [11] lock(f::QuartoNotebookRunner.var"#35#36"{Bool, Dict{String, Any}, Server, String}, l::ReentrantLock)
    @ Base ./lock.jl:253
 [12] borrow_file!(f::QuartoNotebookRunner.var"#27#28"{Nothing, String, Bool, Dict{String, Any}, QuartoNotebookRunner.var"#chunk_callback#_handle_response##0"{TCPSocket}, Server}, server::Server, path::String; optionally_create::Bool, options::Dict{String, Any})
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:1148
 [13] borrow_file!
    @ ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:1139 [inlined]
 [14] #run!#22
    @ ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/server.jl:1108 [inlined]
 [15] _handle_response(socket::TCPSocket, notebooks::Server, request::@NamedTuple{type::String, content::Union{Dict{String, Any}, String}}, showprogress::Bool)
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/socket.jl:273
 [16] (::QuartoNotebookRunner.var"#61#62"{Bool, Base.RefValue{Bool}, Server, Base.UUID})()
    @ QuartoNotebookRunner ~/.julia/packages/QuartoNotebookRunner/eYIiC/src/socket.jl:201
ERROR: Internal julia server error

Stack trace:
    at writeJuliaCommand (file:///opt/quarto/bin/quarto.js:41397:19)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async executeJulia (file:///opt/quarto/bin/quarto.js:41291:22)
    at async Object.execute (file:///opt/quarto/bin/quarto.js:41028:20)
    at async renderExecute (file:///opt/quarto/bin/quarto.js:85764:27)
    at async renderFileInternal (file:///opt/quarto/bin/quarto.js:85932:43)
    at async renderFiles (file:///opt/quarto/bin/quarto.js:85800:17)
    at async render (file:///opt/quarto/bin/quarto.js:90702:21)
    at async Command.actionHandler (file:///opt/quarto/bin/quarto.js:90850:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8099:13)
```

**Comment by felixcremer** [comment]
The version is:

```julia
julia> versioninfo()
Julia Version 1.12.0-DEV.1690
Commit 81568a6dc1b (2024-11-25 13:17 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 PRO 5850U with Radeon Graphics
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 16 virtual cores)

```

**Comment by MichaelHatherly** [comment]
#232 changed the behaviour of code loading such that this world age issue doesn't appear any more.
